services :
  
  service-exposing-application-server:
    
    #...
    #...

    # Add this internal network for proxy pass to nginx server
    networks:
      - internal_proxy_pass_network


  other-services:
    # Etc...



# And add network definition in footer
networks:
  internal_proxy_pass_network:
    external: true