services :
  
  service-exposing-application-server:
    
    #...
    #...

    volumes:
      - /shared-files/${DOMAIN_NAME}/static:/static:rw
      - /shared-files/${DOMAIN_NAME}/media:/media:rw

    # Add this internal network for proxy pass to nginx server
    networks:
      default: {}
      internal_proxy_pass_network:
        aliases:
          - ${DOCKER_NETWORK_SERVICE_ALIAS}


  other-services:
    # Etc...
    networks:
      default: {}



# And add network definition in footer
networks:
  default: {}
  internal_proxy_pass_network:
    external: true